pipeline:
  name: gkalipalli-CI-Pipeline-
  identifier: gkalipalliCIPipeline
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: CI
            identifier: CI
            description: ""
            type: IACM
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: gkalipalligkeconnector
                  namespace: harness-ci
                  volumes: []
                  serviceAccountName: harness-gke-sa
                  annotations: {}
                  labels: {}
                  automountServiceAccountToken: true
                  nodeSelector: {}
                  containerSecurityContext:
                    capabilities:
                      drop: []
                      add: []
                  os: Linux
                  hostNames: []
              workspace: gkalipalliworkspace
              execution:
                steps:
                  - step:
                      type: IACMTerraformPlugin
                      name: init
                      identifier: init
                      timeout: 10m
                      spec:
                        command: init
                  - step:
                      type: IACMTerraformPlugin
                      name: plan
                      identifier: plan
                      timeout: 10m
                      spec:
                        command: plan
                  - step:
                      type: IACMTerraformPlugin
                      name: apply
                      identifier: apply
                      timeout: 10m
                      spec:
                        command: apply
            tags: {}
        - stage:
            name: Build Stage
            identifier: Build_Stage
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: false
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec:
                  size: small
                  imageSpec:
                    imageName: ubuntu-24
              execution:
                steps:
                  - parallel:
                      - step:
                          type: BuildAndPushGAR
                          name: BuildAndPushGAR_1
                          identifier: BuildAndPushGAR_1
                          spec:
                            connectorRef: gkalipalligcpconnector
                            host: us.gcr.io
                            projectID: arched-backup-481810-g4
                            imageName: harness
                            tags:
                              - v1
                      - step:
                          type: Run
                          name: Docker Build  Push
                          identifier: Docker_Build_Push
                          spec:
                            shell: Sh
                            command: |-
                              docker pull lvthillo/python-flask-docker
                              docker run --name my-container -d -p 8080:8080 lvthillo/python-flask-docker

                              echo "Image succesfully created..."
                          description: Pushing to GAR
  properties:
    ci:
      codebase:
        connectorRef: gkalipalligitconnector
        repoName: harness-demo
        build: <+input>
